LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := par2turbo
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_SRC_FILES := par2turbo
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := zstd
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_SRC_FILES := zstd
LOCAL_MODULE_SUFFIX :=
include $(BUILD_PREBUILT)
